version: "3"

services:
  redis-db:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
    user: "1000:1000"  # Change this to the appropriate user ID and group ID
    command: ["--save", "1", "1"]

  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis-db
    image: rheasamuel/ml_flask_app:1.0
    ports:
      - "5000:5000"
    volumes:
      - ./config.yaml:/config.yaml
    environment:
      - REDIS_IP=redis-db
    entrypoint: ["python", "api.py"]  # Default command for the Flask app

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis-db
    image: rheasamuel/ml_flask_worker:1.0
    volumes:
      - ./src/worker.py:/app/worker.py  # Corrected path for the Worker script
    environment:
      - REDIS_IP=redis-db
    entrypoint: ["python", "worker.py"]  # Command for the Worker script

